<?php
//
// ETS2MP Homepage language file.
// File:				      spanish.php
// Language name: 		Spanish
// Translated name: 	Español
//

$_lang["download"] = "Descarga";
$_lang["home"] = "Inicio";
$_lang["status"] = "Estado";
$_lang["username"] = "Usuario";
$_lang["password"] = "Contraseña";
$_lang["login"] = "Entrar";
$_lang["register"] = "Registrarme";
$_lang["download.latest.version"] = "Descargar la última versión";
$_lang["current.release"] = "Versión actual:";
$_lang["language"] = "Lenguaje";
$_lang["join"] = "ENTRAR";
$_lang["mainpage.join"] = "Únete a miles de camioneros online!";
$_lang["ts3.advertisement"] = "Habla con los otros conductores - Haz click para unirte al servidor TS3.";
$_lang["facebook.advertisement"] = "Las últimas noticias en nuestro Facebook.";
$_lang["registration.blocked"] = "El registro esta bloqueado - estamos trabajando en algunos aspectos que bloquean el registro. Lo desbloquearemos tan pronto como terminemos y publiquemos la nueva versión.";
$_lang["invalid.username.password"] = "Correo o contraseña invalido/a.";
$_lang["already.logged"] = "Ya estas registrado.";
$_lang["welcome"] = "Bienvenido";
$_lang["logout"] = "Salir";
$_lang["bans"] = "Baneos";
$_lang["version"] = "Versión";
$_lang["update.time"] = "Fecha de actualización";
$_lang["req.game.version"] = "Versión de juego soportada";
$_lang["requires"] = "Requiere";
$_lang["or.newer"] = "o más nueva";
$_lang["game.client"] = "Cliente de juego";
$_lang["download.no.permissions"] = "Necesitas registrarte para descargar el mod.";
$_lang["why.create.account"] = "¿Porqué crearse una cuenta?<br />Una cuenta será usada para registrarse en todos los servicios (Foro, Juego, Economía, y otros). Planeamos usarlo para registrar la economia y otras estadísticas de cada jugador próximamente. También podrás modificar tu perfil.";
$_lang["website.title"] = "ETS2MP - Mundo del Camionero Virtual - Mod Multijugador para el juego de SCS Software Euro Truck Simulator 2.";
$_lang["cookies.warning"] = "Esta página usa <a href=\"http://en.wikipedia.org/wiki/HTTP_cookie\">cookies</a>. Si continuas en esta página estas de acuerdo con nuestro uso de cookies.";
$_lang["forum"] = "Foro";
$_lang["cannot.create.account.when.logged"] = "No puedes crear una nueva cuenta mientras estas registrado.";
$_lang["successfully.registered"] = "Te has registrado correctamente. Comprueba tu correo para verificar tu nueva cuenta.";
$_lang["error.unknown"] = "Error desconocido";
$_lang["credentials.taken"] = "Usuario, correo, o SteamID ya en uso.";
$_lang["error.no.steam.data"] = "Para crear una cuenta en ETS2MP debes tener Euro Truck Simulator 2 en tu biblioteca de Steam. Si es así, asegurate de que tu cuenta de Steam es pública. Si es privada, hazla pública y presiona";
$_lang["register.steam.info"] = "Para registrarte necesitas entrar en tu cuenta de Steam. Presiona el siguiente botón para redireccionarte a su página de registro.";
$_lang["rules.info"] = "Al presionar el botón de registro aceptas los términos de uso de nuestra comunidad. Haz click aquí para consultarlos.";
$_lang["mail"] = "Correo";
$_lang["repeat.mail"] = "Repite el Correo";
$_lang["new.password"] = "Nueva contraseña";
$_lang["repeat.new.password"] = "Repite la nueva contraseña";
$_lang["new.password.summary"] = "Si dejas los espacios en blanco la contraseña no cambiará.";
$_lang["old.password"] = "Contraseña anterior";
$_lang["repeat.old.password"] = "Repite la contraseña anterior";
$_lang["save.account.data"] = "Guardar datos de cuenta";
$_lang["edit.account"] = "Editar cuenta";
$_lang["forgot.password"] = "Has olvidado la contraseña? Haz Click <a href=\"index.php?page=resetPassword\">aquí</a>.";
$_lang["forgot.password.summary"] = "Has olvidado la contraseña? Introduce tu correo y presiona \"Reminder password\".";
$_lang["reminder.button"] = "Recordar contraseña";
$_lang["reset.password"] = "Resetear contraseña";
$_lang["password.reminder.mail.title"] = "Petición de contraseña olvidada.";
$_lang["password.reminder.content"] = "Hola.\n\nAlguien de IP {0} ha pedido resetear la contraseña de tu cuenta.\n\nPara hacerlo haz click en el siguiente enlace: {1}.\nSi no fuiste tu ignora este correo.\n\nUn saludo\nEquipo ETS2MP";
$_lang["new.password.mail.title"] = "Tu nueva contraseña.";
$_lang["new.password.mail.content"] = "Hola.\n\nTu nueva contraseña es: {0}\n\nRecuerda cambiarla nada más entrar al sistema.\n\nUn saludo\nEquipo ETS2MP";
$_lang["account.activated"] = "Tu cuenta ha sido activada correctamente.";
$_lang["unable.to.activate"] = "Imposible activar la cuenta, llave incorrecta o cuenta ya activada.";
$_lang["not.activated"] = "Tu cuenta no esta activada todabía. Si no tienes un correo de activación haz click <a href=\"index.php?action=resendActivation\">aquí</a> para enviar una nueva llave.";
$_lang["force.password.change"] = "Porfavor cambia la contraseña inmediatamente. Haz click <a href=\"index.php?page=editAccount\">aquí</a> para hacerlo.";
$_lang["forgot.password.link.sent"] = "Comprueba tu correo. Hemos enviado un link para resetear la contraseña.";
$_lang["forgot.password.sent"] = "Comprueba tu correo. Hemos enviado una nueva contraseña.";
$_lang["forgot.password.invalid.key"] = "Llave de reseteo de contraseña invalida.";
$_lang["activation.key.resent"] = "Hemos enviado una nueva llave de activación a tu correo.";
$_lang["activation.mail.title"] = "Activación de cuenta ETS2MP.";
$_lang["activation.mail.content"] = "Hola.\n\nEsta es tu llave de activación: {0}\n\Gracias\nEquipo ETS2MP";
$_lang["no.login"] = "Debes estar registrado para acceder a esta página.";
$_lang["settings.saved.with.mail"] = "Tu cuenta ha sido guardada. Comprueba tu correo de nuevo para verificarla.";
$_lang["new.email.in.use"] = "Este correo ya está en uso.";
$_lang["email.does.not.match"] = "Los correos introducidos no coinciden.";
$_lang["invalid.email.format"] = "El correo introducido no es válido.";
$_lang["new.password.does.not.match"] = "La nueva contraseña introducida no coincide.";
$_lang["too.short.password"] = "La nueva contraseña es demasiado corta. Requiere un mínimo de 5 caráctere.s";
$_lang["old.password.does.not.match"] = "La vieja contraseña no coincide.";
$_lang["settings.saved"] = "La cuenta ha sido guardada.";
$_lang["invalid.old.password"] = "La vieja contraseña es invalida, imposible guardar la cuenta.";
$_lang["no.password.change.forced"] = "Para resetear la contraseña debes salir del sistema.";
$_lang["password.reminder.edit.account"] = "Has olvidado la contraseña? Haz click <a href=\"index.php?page=resetPassword\">aquí</a>.";
$_lang["contact"] = "Contacto";
$_lang["your.mail"] = "Tu correo";
$_lang["content"] = "Contenido";
$_lang["send"] = "Enviar";
$_lang["contact.message.sent"] = "Gracias por contactar con noostros. Por favor, espera nuestra respuesta.";
$_lang["topic"] = "Asunto";
$_lang["contact.message.too.short"] = "El mensaje es demasiado corto. Debe tener un mínimo de 10 carácteres.";
$_lang["contact.topic.too.short"] = "El asunto es demasiado corto. Debe tener un mínimo de 10 carácteres.";
$_lang["invalid.mail.forgot.password"] = "No hemos encontrado ninguna cuenta con dicho correo.";
$_lang["steamid.in.use"] = "Ya existe una cuenta de ETS2MP asignada al SteamID introducido. Si tienes algún problema con el registro porfavor <a href=\"http://ets2mp.com/support/\">crea un ticket de soporte</a>.";
$_lang["mail.does.not.match"] = "El correo introducido no coincide.";
$_lang["support"] = "Soporte";
$_lang["profile"] = "Perfil";
$_lang["group"] = "Grupo";
$_lang["banned"] = "Baneado";
$_lang["state"] = "Estado";
$_lang["account.is.activated"] = "Cuenta activada.";
$_lang["account.isnt.activated"] = "Cuenta no activada.";
$_lang["penalty.history"] = "Historial de penalizaciones.";
$_lang["no.punishments"] = "No hay castigos que mostrar.";
$_lang["date"] = "Fecha";
$_lang["reason"] = "Razón";
$_lang["type"] = "Tipo";
$_lang["penalty.limit"] = "Solo el dueño del perfil puede visualizar más penalizaciones.";
